### ISSUE TITLE
Application won't run/start

### ISSUE THREAD

**Issue by bmccorm2** [ParthJadhav/Verve#42]
I'm sure this is a user error but here goes.  I install the app (x86_64), run it, hit `cmd+shift+g`, and nothing.  I check in activity monitor i can't find any process by the name 'verve.'  

If i install the aarch64 version, i get this error: https://github.com/ParthJadhav/Verve/issues/16.

Much appreciated if you can point me in the right direction or some error messages or logs :)  Thanks!

**Comment by ParthJadhav** [comment]
Hey @bmccorm2 , Can you try running the Executable file and share the output?

**Comment by bmccorm2** [comment]
I think this is the right binary?
```
bryan@cave ~> /Applications/verve.app/Contents/MacOS/verve 
exec: Failed to execute process '/Applications/verve.app/Contents/MacOS/verve', unknown error number 86
```

**Comment by ParthJadhav** [comment]
Hey @bmccorm2 , Sorry for the delay... I'll investigate.. That's quite strange though.

Is there any different output if you run the Executable from Finder?

**Comment by bmccorm2** [comment]
Ah - maybe that is it.  When i run the executable from finder it asks to install rosetta.  So i'm guessing it won't run because i don't have rosetta installed? 

I'd rather not install rosetta.  But if i try the arm version I just get this error https://github.com/ParthJadhav/Verve/issues/16 which says is fixed?

**Comment by ParthJadhav** [comment]
Oh no, It's not fixed. I need to Pay apple to get it fixed I assume. I haven't signed the app because it costs 100$ per year. 

You can try this:


`xattr -c /Applications/verve.app`

**Comment by bmccorm2** [comment]
Same message :/ 
```
bryan@cave ~> sudo xattr -c /Applications/verve.app/
Password:
bryan@cave ~> /Applications/verve.app/Contents/MacOS/verve
exec: Failed to execute process '/Applications/verve.app/Contents/MacOS/verve', unknown error number 86
```

**Comment by ParthJadhav** [comment]
> Same message :/
> 
> ```
> bryan@cave ~> sudo xattr -c /Applications/verve.app/
> Password:
> bryan@cave ~> /Applications/verve.app/Contents/MacOS/verve
> exec: Failed to execute process '/Applications/verve.app/Contents/MacOS/verve', unknown error number 86
> ```

I'll see if I can replicate this error...
